BibliometricsApp/app/v1/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

BibliometricsApp/app/v1/controllers/documentController.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template,\
                  session, redirect, url_for,\
                  request, jsonify, make_response,\
                  flash, current_app
from datetime import datetime
from math import log
from app.v1.helpers.dicts import collections, country_collections,\
                              thematic_areas as areas, country_code_inv,\
                              country_name, country_code_rev,\
                              not_collections
from app.v1.helpers.elasticQueries import elasticQueries
from app.v1.helpers.ISO_3166_ALPHA2 import ISO_3166_ALPHA2
from app.v1.helpers.ISO_3166_ALPHA3 import ISO_3166_ALPHA3
from app.v1.helpers.ISO_639_ALPHA2 import ISO_639_ALPHA2
from app.v1.helpers.formHelper import *
from app.v1.classes.filters import Filters
from app.v1.classes.publicationStats import PublicationStats

import os.path
import json

VERSION = "v1"
mod_document = Blueprint('documentController', __name__, url_prefix='/'+VERSION+'/documents')

#-- ----------------------------------------------------------------

@mod_document.route('/', methods = ['POST'])
def d_index():
  #Leemos Formulario y obtenemos filtros
  form =  request.form
  filters = process_filters_form(form)  
  
  if(filters.tabulation == "t1"):
    return tabulation_t1(filters)
  elif(filters.tabulation == "t2"):
    return tabulation_t2(filters)
  elif(filters.tabulation == "t3"):
    return tabulation_t1(filters)
  elif(filters.tabulation == "t4"):
    return tabulation_t4(filters)
  elif(filters.tabulation == "t5"):
    return tabulation_t5(filters)
  elif(filters.tabulation == "t6"):
    return tabulation_t1(filters)
  elif(filters.tabulation == "t7"):
    return tabulation_t7(filters)
  else:
    flash('Impossible to answer the request at this time', 'error')
    return redirect(url_for("indexController.index"))

#-- ----------------------------------------------------------------
#-- ----------------------------------------------------------------
#-- ----------------------------------------------------------------

def tabulation_t1(filters = Filters):
  if not os.path.exists(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json'):
    publication = PublicationStats(current_app.config.get("SERVER"), current_app.config.get("PUBLICATIONSTATS"))
    response = publication.run_query(elasticQueries[filters.scope]["tabulations"][filters.tabulation]["query"], filters = filters)
    data_treemap, data_table = {}, {}
    data_treemap["by_area"], data_table["by_area"] = data_process_treemap_table(response, "by_collection", "by_area", True)
    data_treemap["by_language"], data_table["by_language"] = data_process_treemap_table(response, "by_collection", "by_language", True)
    data_treemap["by_affiliation"], data_table["by_affiliation"] = data_process_treemap_table(response, "by_collection", "by_affiliation", True)
    data_treemap["by_journal"], data_table["by_journal"] = data_process_treemap_table(response, "by_collection", "by_journal", True)
    data_treemap["by_year"], data_table["by_year"] = data_process_treemap_table(response, "by_collection", "by_year", False)

    data_map = {"keys": ["documents"],
                "by_year": data_treemap["by_year"],
                "by_area": data_treemap["by_area"]}
    #Añadimos keys y areas a la estructura
    for d in data_map["by_area"]:
      if not d["sub-group"] in data_map["keys"]:
        data_map["keys"].append(d["sub-group"])
      d[d["sub-group"]] = d["documents"]

    #Creamos un json de caché
    j = {
        'Filters'     : filters.serialize,
        'data_treemap': data_treemap,
        'data_table'  : data_table,
        'data_map'    : data_map,
    }
    with open(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json', 'w') as json_file:
        json.dump(j, json_file, ensure_ascii=True, sort_keys=True, indent=4)
  data_treemap, data_table, data_map = data_from_cache(filters, True, True, True)
  return render_template("v1/document/tabulation_t1.html", filters = filters, data_treemap = data_treemap, data_table = data_table, data_map = data_map).encode( "utf-8" )

#-- ----------------------------------------------------------------

def tabulation_t2(filters = Filters):
  if not os.path.exists(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json'):
    publication = PublicationStats(current_app.config.get("SERVER"), current_app.config.get("PUBLICATIONSTATS"))
    response = publication.run_query(elasticQueries[filters.scope]["tabulations"][filters.tabulation]["query"], filters = filters)
    data_treemap, data_table = {}, {}
    data_treemap["by_collection"], data_table["by_collection"] = data_process_treemap_table(response, "by_area", "by_collection", True)
    data_treemap["by_language"], data_table["by_language"] = data_process_treemap_table(response, "by_area", "by_language", True)
    data_treemap["by_affiliation"], data_table["by_affiliation"] = data_process_treemap_table(response, "by_area", "by_affiliation", True)
    data_treemap["by_journal"], data_table["by_journal"] = data_process_treemap_table(response, "by_area", "by_journal", True)
    data_treemap["by_year"], data_table["by_year"] = data_process_treemap_table(response, "by_area", "by_year", False)

    data_map = {}
    for d in data_treemap["by_collection"]:
      if data_map.has_key(d["group"]):
        data_map[d["group"]].append(d)
      else:
        data_map[d["group"]] = [d]

    #Creamos un json de caché
    j = {
        'Filters'     : filters.serialize,
        'data_treemap': data_treemap,
        'data_table'  : data_table,
        'data_map'    : data_map,
    }
    with open(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json', 'w') as json_file:
        json.dump(j, json_file, ensure_ascii=True, sort_keys=True, indent=4)
  data_treemap, data_table, data_map = data_from_cache(filters, True, True, True)
  return render_template("v1/document/tabulation_t2.html", filters = filters, data_treemap = data_treemap, data_table = data_table, data_map = data_map).encode( "utf-8" )

#-- ----------------------------------------------------------------

def tabulation_t4(filters = Filters):
  if not os.path.exists(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json'):
    publication = PublicationStats(current_app.config.get("SERVER"), current_app.config.get("PUBLICATIONSTATS"))
    response = publication.run_query(elasticQueries[filters.scope]["tabulations"][filters.tabulation]["query"], filters = filters)
    data_treemap, data_table = {}, {}
    data_treemap["by_collection"], data_table["by_collection"] = data_process_treemap_table(response, "by_language", "by_collection", True)
    data_treemap["by_area"], data_table["by_area"] = data_process_treemap_table(response, "by_language", "by_area", True)
    data_treemap["by_affiliation"], data_table["by_affiliation"] = data_process_treemap_table(response, "by_language", "by_affiliation", True)
    data_treemap["by_journal"], data_table["by_journal"] = data_process_treemap_table(response, "by_language", "by_journal", True)
    data_treemap["by_year"], data_table["by_year"] = data_process_treemap_table(response, "by_language", "by_year", False)

    data_map = {}
    for d in data_treemap["by_collection"]:
      if data_map.has_key(d["group"]):
        data_map[d["group"]].append(d)
      else:
        data_map[d["group"]] = [d]

    #Creamos un json de caché
    j = {
        'Filters'     : filters.serialize,
        'data_treemap': data_treemap,
        'data_table'  : data_table,
        'data_map'    : data_map,
    }
    with open(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json', 'w') as json_file:
        json.dump(j, json_file, ensure_ascii=True, sort_keys=True, indent=4)
  data_treemap, data_table, data_map = data_from_cache(filters, True, True, True)
  return render_template("v1/document/tabulation_t4.html", filters = filters, data_treemap = data_treemap, data_table= data_table, data_map = data_map, ISO_639_ALPHA2 = ISO_639_ALPHA2).encode( "utf-8" )

#-- ----------------------------------------------------------------

def tabulation_t5(filters = Filters):
  if not os.path.exists(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json'):
    publication = PublicationStats(current_app.config.get("SERVER"), current_app.config.get("PUBLICATIONSTATS"))
    response = publication.run_query(elasticQueries[filters.scope]["tabulations"][filters.tabulation]["query"], filters = filters)
    data_treemap, data_table = {}, {}
    data_treemap["by_collection"], data_table["by_collection"] = data_process_treemap_table(response, "by_affiliation", "by_collection", True)
    data_treemap["by_area"], data_table["by_area"] = data_process_treemap_table(response, "by_affiliation", "by_area", True)
    data_treemap["by_language"], data_table["by_language"] = data_process_treemap_table(response, "by_affiliation", "by_language", True)
    data_treemap["by_journal"], data_table["by_journal"] = data_process_treemap_table(response, "by_affiliation", "by_journal", True)
    data_treemap["by_year"], data_table["by_year"] = data_process_treemap_table(response, "by_affiliation", "by_year", False)

    data_map = []
    for d in data_treemap["by_year"]:
      d["year"] = d["sub-group"]
      data_map.append(d)

    #Creamos un json de caché
    j = {
        'Filters'     : filters.serialize,
        'data_treemap': data_treemap,
        'data_table'  : data_table,
        'data_map'    : data_map,
    }
    with open(current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/'+filters.md5+'.json', 'w') as json_file:
        json.dump(j, json_file, ensure_ascii=True, sort_keys=True, indent=4)
  data_treemap, data_table, data_map = data_from_cache(filters, True, True, True)

BibliometricsApp/app/v1/controllers/exporterController.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template,\
                  session, redirect, url_for,\
                  request, jsonify, make_response,\
                  current_app
from app.v1.helpers.dicts import collections as collections_dict, country_collections, thematic_areas as areas, country_code_inv, country_name,country_code_rev,not_collections

import pyexcel as pe
import StringIO
import ast

VERSION = "v1"
mod_export = Blueprint('exporterController', __name__, url_prefix='/'+VERSION)


def gfile_download(filename = 'export', extension = 'xlsx', book = {}):
    #generamos el excel
    book = pe.Book(book)
    io = StringIO.StringIO()
    book.save_to_memory(extension, io)
    output = make_response(io.getvalue())
    output.headers["Content-Disposition"] = "attachment; filename=%s.%s" %(filename, extension)
    output.headers["Content-type"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    return output


@mod_export.route('/export', methods = ['POST'])
def export():
    #Leemos Formulario y obtenemos filtros
    form =  request.form
    
    data = ast.literal_eval(form.get('data', '{}').encode('utf-8'))

    return simple_dict_export(data = data)
    #return gfile_download("[SciELO]Empty", "xlsx", book)


def simple_dict_export(data = {}):
    book = {}
    sheet_name = "Sheet1"
    book[sheet_name] = []
    book[sheet_name].append(["Header1", "Header2", "# Documents"])
    for key, values in data.items():
        for k, v in values.items():
            book[sheet_name].append([key, k, v])
    return gfile_download("[SciELO]Documents", "xlsx", book)



def documents_export(data = {}, journals = {}):
    book = {}
    for country, cant in data.items():
        sheet_name = "%s(%s)" %(country, cant)
        book[sheet_name] = []
        book[sheet_name].append([country, "%s Publications" %(cant)])
        book[sheet_name].append([])
        book[sheet_name].append(["Journal", "#Publications"])
        for j in  journals[country]:
            book[sheet_name].append([j, journals[country][j]["citation"]])
    return gfile_download("[SciELO]Documents", "xlsx", book)

def citations_export(data = {}, journals = {}):
    book = {}
    for country, cit in data.items():
        sheet_name = "%s(%s)" %(country, cit)
        book[sheet_name] = []
        book[sheet_name].append([country, "%s Citations" %(cit)])
        book[sheet_name].append([])
        book[sheet_name].append(["Journal", "#Citations"])
        for j in  journals[country]:
            book[sheet_name].append([j, journals[country][j]["citation"]])
    return gfile_download("[SciELO]Citations", "xlsx", book)


def coauthors_export(data = [{}, {}, {}]):
    book = {}
    sheet_name = 'Co-Authors'
    book[sheet_name] = []
    book[sheet_name].append(["Country", "Provided number of Co-Author relationships", "Co-Author country diversity", "Co-Authors from"])
    for country, rel in data[1].items():
        line = ""
        for k, v in data[0][country].items():
            line += "%s(%s); " %(k, v)
        book[sheet_name].append([country, rel, round(100.0*(float(len(data[0][country]))/240.0), 1), line])
    return gfile_download("[SciELO]Co-Authors", "xlsx", book)


def collections_export(data = [{}, {}, {}, {}]):
    book = {}
    sheet_name = 'Collections'
    book[sheet_name] = []
    book[sheet_name].append(["Collection", "Times Chosen (Documents)", "Chosen by authors from", "Countries"])
    for country, choices in data[1].items():
        line = ""
        for c in data[3][country]:
            line += "%s; " %(c)
        book[sheet_name].append([country, choices, "%s Countries" %(len(data[3][country])), line])
    return gfile_download("[SciELO]Collections", "xlsx", book)

BibliometricsApp/app/templates/v1/graph/citations_graph.html
{% extends "v1/layouts/layout.html" %}


{% block filters %}
	{% include "v1/partials/filters.html" %}
{% endblock %}


{% block content %}
	<div class="container">
  	<div class="col s12 m12 l12">
  		<br><br>
			<h4>
				Citations distribution by affiliation countries
				<!-- Modal Info Trigger -->
				<a href="#modal-info" class="modal-trigger  right btn btn-flat waves-effect waves-light"><i class="material-icons">info_outline</i></a>
			</h4>
  	</div>
		<hr>
  </div>
	{% include "v1/partials/current_filters.html" %}
{% endblock %}


{% block visualization_block %}
	<div class="container">
	  	<div class="col s12 m12 l6">
	  		<div id="world">
					<div id="world_legend"></div>
	  		</div>
				<div id="network"></div>
	  	</div>
	</div>
{% endblock %}


{% block graph %}
	<div class="container">
	  	<div class="col s12 m12 l6">
	  		<center>
	  			<div id="country-graph"></div>
				<div id="graph"><svg style="width:600px;height:400px;"</svg></div>
			</center>
	  	</div>
	</div>
{% endblock %}


{% block results %}
	<div class="container">
  	<div class="col s12 m12 l12">
  		<ul class="collapsible" data-collapsible="accordion">
  			{% for country, cit in data.items() %}
  				<li>
	  				<div class="collapsible-header">
	  					<div style="float: left; width: 10%;"><img src="/static/img/flags/{{country.lower()}}.gif"></div>
	  					<div style="float: left; width: 40%;">{{ country }}</div>
	  					<div style="float: left; width: 50%; text-align: center;">{{ cit }} Citations</div>
	  				</div>
	  				<div class="collapsible-body">
	  					<table class="responsive-table striped">
		  					{% for j in  journals[country]%}
		  						<tr>
		  							<td>{{ j }}</td>
		  							<td>{{ journals[country][j]["citation"] }} Citations</td>
		  						</tr>
								{% endfor %}	  						
	  					</table>
	  				</div>
	  			</li>
  			{% endfor %}
  		</ul>
  	</div>
  	<!-- Exportar Data -->
  	<form id="filters-form" action="{{ url_for('exporterController.export') }}" method=post>
  		<input id="export-input" type="hidden" name="vistype" value="{{ filters.vistype }}">
  		<input id="export-input" type="hidden" name="journals" value="{{ journals }}">
  		<input id="export-input" type="hidden" name="data" value="{{ data }}">
  		<button class="btn deep-purple right waves-effect waves-light">Export</button>
  	</form>
  	<br><br>
  </div>
{% endblock %}


{% block modals %}
	<!-- Modal Info Structure -->
	<div id="modal-info" class="modal bottom-sheet">
	  <div class="modal-content">
	    <h4>Citations distribution by affiliation countries</h4>
      <p>The visualization shows the number of citations (the sum) of documents published in countries collections/journals according to the filters selected.</p>

      <p><i>Example:</i></p>
      <p>The amount of citations to documents writen in english in the spanish collection in period 2007-2016 is: 3994</p>
      <img src="/static/img/citations.png" width="50%">

      <p>The color of the countries represents the amount of citations according to the color scale displayed below the map. </p>
      <p>When the mouse is hovering over the country, a detailed information is showed.</p>
      <p>The same information (and other aditional) is also showed in a table below the map.</p>
	  </div>
	  <div class="modal-footer">
	    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
	  </div>
	</div>

{% endblock %}


{% block js_footer %}
	{% include "v1/partials/filters.js" %}
	{% include "v1/partials/current_filters.js" %}
	<script type="text/javascript">
		//ACTIVAR MODAL
		$('.modal-trigger').leanModal();

		//MAPA
		journals = {{ journals|tojson }};
		citations = {{ data|tojson }};
		collection = {{ collection|tojson }};
		var map = world_map(1, citations);
		citation(map, citations,collection);
	</script>
{% endblock %}

BibliometricsApp/app/templates/v1/graph/coauthors_graph.html
{% extends "v1/layouts/layout.html" %}


{% block filters %}
	{% include "v1/partials/filters.html" %}
{% endblock %}


{% block content %}
	<div class="container">
  	<div class="col s12 m12 l12">
  		<br><br>
			<h4>
				Geo Co-Authors Networks
				<!-- Modal Info Trigger -->
				<a href="#modal-info" class="modal-trigger  right btn btn-flat waves-effect waves-light"><i class="material-icons">info_outline</i></a>
			</h4>
  	</div>
		<hr>
  </div>
  
	{% include "v1/partials/current_filters.html" %}

	<div class="container">  	
  	<button id="transform-to-network" class="btn deep-purple lighten-2">Transform to Network</button>
		<button id="transform-to-map" class="btn deep-purple lighten-2" style="display:none">Transform to Map</button>	
		<button id="change_vis1" class="btn deep-purple lighten-2" style="display:none">Cambiar visualización</button>
		<button id="change_vis2" class="btn deep-purple lighten-2" style="display:none">Cambiar visualización</button>
	</div>
{% endblock%}


{% block visualization_block %}
	<div class="container">
  	<div class="col s12 m12 l6">
  		<div id="world">
				<div id="world_legend"></div>
  		</div>
			<div id="network"></div>
  	</div>
  </div>
{% endblock %}


{% block results %}
	<div class="container">
		<hr>
  	<div class="col s12 m12 l6">
  		<table id="dataTable1" class="bordered striped">
  			<thead>
  				<td></td>
  				<th>Country</th>
  				<th>Provided number of co-author relationships</th>
  				<th>Co-author country diversity</th>  	
  				<th>Co-authors from </th>  				
  			</thead>
  			<tbody>
          {% for country, rel in data[1].items() %}  				
	  				<tr>
              <td><img src="/static/img/flags/{{country.lower()}}.gif"></td>              
	  					<td>{{ country }}</td>
	  					<td>{{ rel }}</td>
	  					<td>
	  						{{ 100*((data[0][country]|count)/240)|round(3) }} <!--  hacer json con valores calculados-->
	  					</td>	  		
	  					<th> <!-- Principales -->	
	  						{% for prin in data[0][country] %}
	  							<img src="/static/img/flags/{{prin.lower()}}.gif">
	  						{% endfor %}
	  					</th>		
	  				</tr>
          {% endfor %}
  			</tbody>
  		</table>
  	</div>
  	<!-- Exportar Data -->
  	<form id="filters-form" action="{{ url_for('exporterController.export') }}" method=post>
  		<input id="export-input" type="hidden" name="vistype" value="{{ filters.vistype }}">
  		<input id="export-input" type="hidden" name="data" value="{{ data }}">
  		<button class="btn deep-purple right waves-effect waves-light">Export</button>
  	</form>
  	<br><br>
  </div>
{% endblock %}


{% block modals %}
	<!-- Modal Info Structure -->
	<div id="modal-info" class="modal bottom-sheet">
	  <div class="modal-content">
	    <h4>Geo Co-Authors Networks</h4>
		<p>The visualization shows the co-author relationships between authors of documents.</p>
		<p>When the mouse is hovering over the country, a detailed information is showed and links between countries appear. These links represents co-author relationships between authors of the selected country and authors of other countries.</p>
		<p>The color of the  country in the map represents the amount of co-author provided by  country according to the color scale displayed below the map. </p>
		<p>The visualization of the map can be transformed to a network representation, and viceversa.</p>
    <p><i>Example:</i></p>
    <p> Authors from Brazil have co-authors from Brazil, Republica Dominicana, Canada and France (Period 2004-2016, language french). </p>
    <img src="/static/img/coauthors.png" width="70%">		
		<p>
			The Table below the map shows information about the co-author relationships:
			<ol>
				<li>The number of co-authors provided by the country.</li>
				<li>The degree of diversity of the country. The degree is high if the authors of the  country work with authors from different countries,  and low , if the authors of the  country work with authors from few countries.</li>
				<li>Countries that generates co-author relationships with a country.</li>
			</ol>
		</p>
	  </div>
	  <div class="modal-footer">
	    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
	  </div>
	</div>
{% endblock %}


{% block js_footer %}
	{% include "v1/partials/filters.js" %}
	{% include "v1/partials/current_filters.js" %}
	<script type="text/javascript">
		//ACTIVAR MODAL
		$('.modal-trigger').leanModal();

		//MAPA
		coauthor = {{ data|tojson }};
		var map = world_map(3, []);
		created_networks = false;
		coauthor_network(map, coauthor);

		$(document).ready(function() {
		    $('#dataTable1').DataTable({
		    	"order": [[ 2, "desc" ]]
		    });
		    $('select').material_select();
		});

	</script>
{% endblock %}

BibliometricsApp/app/templates/v1/graph/collections_graph.html
{% extends "v1/layouts/layout.html" %}


{% block filters %}
  {% include "v1/partials/filters.html" %}
{% endblock %}


{% block content %}
	<div class="container">
  	<div class="col s12 m12 l12">
  		<br><br>
			<h4>
        Geo journal affiliation choice network
        <!-- Modal Info Trigger -->
        <a href="#modal-info" class="modal-trigger  right btn btn-flat waves-effect waves-light"><i class="material-icons">info_outline</i></a>
      </h4>
  	</div>
		<hr>
  </div>
  {% include "v1/partials/current_filters.html" %}
{% endblock%}


{% block visualization_block %}
	<div class="container">
  	<div class="col s12 m12 l6">
  		<div id="world">
				<div id="world_legend"></div>
  		</div>
			<div id="network"></div>
  	</div>
  </div>
{% endblock %}


{% block results %}
	<div class="container">
		<hr>
  	<div class="col s12 m12 l6">
  		<table id="dataTable1" class="bordered striped">
  			<thead>
          <th></th>          
  				<th>Collection</th>
  				<th>Times Chosen (Documents) </th>
          <th>Chosen by authors from</th>    
          <th></th>          
  			</thead>
  			<tbody>
          {% for country, choices in data[1].items() %}
            <tr>
              <td><img src="/static/img/flags/{{country.lower()}}.gif"></td>              
              <td>{{ country }}</td>
              <td>{{ choices }}</td>
              <td>{{ data[3][country]|count }} countries</td>
              <td>
                {% for country in data[3][country] %}
                  <img src="/static/img/flags/{{country.lower()}}.gif">
                {% endfor %}          
              </td>
            </tr>
          {% endfor %}
  			</tbody>
  		</table>
  	</div>
    <!-- Exportar Data -->
    <form id="filters-form" action="{{ url_for('exporterController.export') }}" method=post>
      <input id="export-input" type="hidden" name="vistype" value="{{ filters.vistype }}">
      <input id="export-input" type="hidden" name="data" value="{{ data }}">
      <button class="btn deep-purple right waves-effect waves-light">Export</button>
    </form>
  	<br><br>  
  </div>
{% endblock %}

{% block modals %}
  <!-- Modal Info Structure -->
  <div id="modal-info" class="modal bottom-sheet">
    <div class="modal-content">
      <h4>Geo journal affiliation choice network</h4>
      <p>The visualization shows the collection/journals (countries) chosen by authors from different countries. </p>
      <p>When the mouse is hovering over the country, a detailed information is showed and links between countries appear. These links represents the collection choices made by  authors of the selected country.</p>
      <p>The color of the  country in the map represents the amount of choices made by authors from the world, according to the color scale displayed below the map. </p>
      <p><i>Example:</i></p>
      <p> Authors from Argentina choice journals from Brazil, Costa Rica, Colombia (Period 2004-2016, language french). </p>
      <img src="/static/img/collections.png" width="20%">


      <p>
        The Table below the map shows information about the co-author relationships:
        <ol>
          <li>The number of times chosen (documents)  provided by the country.</li>
          <li>Countries that choose a country.</li>
        </ol>
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>
{% endblock %}


{% block js_footer %}
  {% include "v1/partials/filters.js" %}
  {% include "v1/partials/current_filters.js" %}
	<script type="text/javascript">
    //ACTIVAR MODAL
    $('.modal-trigger').leanModal();

    //MAPA
    collection = {{ data|tojson }};
		var map = world_map(4, [collection[0],collection[2]]);
    collection_network(map, collection);

    $(document).ready(function() {
        $('#dataTable1').DataTable({
          "order": [[ 2, "desc" ]]
        });
        $('select').material_select();
    });
	</script>
{% endblock %}